services:
  app:
    build: .
    restart: always
    ports:
      - "9000:9000"  # SMTP listen port
    volumes:
      - ./error:/app/error
      - ./errorarchive:/app/errorarchive
      - ./datmail/config.py:/app/datmail/config.py
      - ./datmail.log:/app/datmail.log
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    depends_on:
      - db

  db:
    image: postgres:12
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

networks:
  traefik:
    external: true
